// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EXE201.Models;

public partial class Destination
{
    public long Id { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public string Location { get; set; }

    public bool IsActive { get; set; }

    public virtual ICollection<Package> Packages { get; set; } = new List<Package>();
}