// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EXE201.Models;

public partial class News
{
    public int NewsId { get; set; }

    public string Title { get; set; }

    public string Url { get; set; }

    public string Summary { get; set; }

    public string Content { get; set; }

    public string PictureUrl { get; set; }
}